
title: Shaked Delarea
description: Security Researcher


show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

avatar: /images/logo.png


baseurl: ""


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: shaqedelarea@gmail.com
  facebook:
  flickr:
  github: shaqed
  instagram:
  linkedin: shaked-delarea-47014389/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: users/4497575/shaqed
   # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/